### ISSUE TITLE
Incompatible, starting with zotero 6.0-beta.1+c6d03753f

### ISSUE THREAD

**Issue by endfreude** [justinribeiro/zotero-google-scholar-citation-count#1]
![image](https://user-images.githubusercontent.com/19976082/153573378-9c6966b0-b001-49e8-b8cb-2b8ef0ade436.png)

The add-on was compatible with the beta version before 6.0-beta.1+c6d03753f (compatibility broke today, 11.02.2022).

https://forums.zotero.org/discussion/comment/399103/#Comment_399103

**Comment by Tsingwaa** [comment]
> ![image](https://user-images.githubusercontent.com/19976082/153573378-9c6966b0-b001-49e8-b8cb-2b8ef0ade436.png)
> 
> The add-on was compatible with the beta version before 6.0-beta.1+c6d03753f (compatibility broke today, 11.02.2022).
> 
> https://forums.zotero.org/discussion/comment/399103/#Comment_399103
<img width="627" alt="5ccd29cecfc4cf8f1ab40e084329d42" src="https://user-images.githubusercontent.com/24680950/159166195-55d1b70f-5d66-4991-81b7-af0732dfda75.png">

**Comment by Ghiclgi** [comment]
See a solution [here](https://github.com/eschnett/zotero-citationcounts/issues/17#issuecomment-1062822577).
> 1. open '.xpi' by a zip software.
> 2. open 'install.rdf' by a text software.
> 3. change the maxVersion like to:
> 
> ```
> <em:maxVersion>6.0.*</em:maxVersion>
> ```
> 
> 4. save, close, and now you can install and find it compatible.

**Comment by endfreude** [comment]
> See a solution [here](https://github.com/eschnett/zotero-citationcounts/issues/17#issuecomment-1062822577).
> 
> > 1. open '.xpi' by a zip software.
> > 2. open 'install.rdf' by a text software.
> > 3. change the maxVersion like to:
> > 
> > ```
> > <em:maxVersion>6.0.*</em:maxVersion>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. save, close, and now you can install and find it compatible.

This works! Important is to zip the files at the folder root level, as mentioned here: https://github.com/eschnett/zotero-citationcounts/issues/17#issuecomment-1073409781
