### ISSUE TITLE
The search results on Google Scholar have been updated, and currently, the plugin is not functioning.

### ISSUE THREAD

**Issue by byerose** [justinribeiro/zotero-google-scholar-citation-count#11]
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/81293778/f1c38481-d18e-44dc-8002-b16bad5097a3)

**Comment by justinribeiro** [comment]
That's interesting; that particular paper has a different GS interface. Other papers seem to have the original interface, and I'm noticing the depending on what you search for (at least as I sit at my desk in California), it seems to jump between both. 

Testing the loop, I see some papers updating, others that should that are not. Let me see if I can hotfix this today with a double look up for both interfaces.

**Comment by justinribeiro** [comment]
I'll be cutting a release here shortly with this patch!

**Comment by justinribeiro** [comment]
v3.2.2 released! https://github.com/justinribeiro/zotero-google-scholar-citation-count/releases/tag/v3.2.2

**Comment by byerose** [comment]
great!
