### ISSUE TITLE
Zotero 7 Support

### ISSUE THREAD

**Issue by justinribeiro** [justinribeiro/zotero-google-scholar-citation-count#14]
Placeholder for prepping for the Zotero 7 release.

- [x] install.rdf → manifest.json
- [x] update.rdf → updates.json
- [x] XUL Overlays → bootstrap.js
- [x] chrome.manifest → runtime chrome registration
- [x] Localization → fluent files
- [x] replace .dtd files
- [x] switch to prefs.js defaults

**Comment by justinribeiro** [comment]
Latest update: It's almost ready! https://youtu.be/wgW74lL_tgI

[![Watch the video](https://img.youtube.com/vi/wgW74lL_tgI/maxresdefault.jpg)](https://youtu.be/wgW74lL_tgI)

**Comment by ZJunSong** [comment]
We are waitting 4 this in zotero 7. TKs

**Comment by rbvk** [comment]
Great, waiting for it. Thanks for your contribution.

**Comment by TrancyWang** [comment]
when can download, cann't wait anymore

**Comment by Walkwise-0** [comment]
I am joining the waiting queue, seems like a great plugin

**Comment by mrisager** [comment]
+1

**Comment by nikbpetrov** [comment]
+1

**Comment by Jorgeromeu** [comment]
+1

**Comment by strawhatboy** [comment]
Great plugin and great feature! Many thanks to the author!

it's available by git clone the repository, git checkout the 'zotero-7-support' branch, and run 'npm run clean && ./build.sh'
a *.xpi file will be generated in the 'build' folder, and it can be imported to zotero7 and working well! 🎉

**Comment by kbdragon** [comment]
Joining the waiting list

**Comment by justinribeiro** [comment]
Brief update: I _believe_ I have all the Z7 kinks worked out. I'm going to make one more push this weekend and then we're going to cut a beta branch on Monday the 20th! :partying_face:

**Comment by justinribeiro** [comment]
Initial version released! https://github.com/justinribeiro/zotero-google-scholar-citation-count/releases/tag/v4.0.0
