### ISSUE TITLE
Google Scholar verification keeps popping up repeatedly

### ISSUE THREAD

**Issue by MrGongqi** [justinribeiro/zotero-google-scholar-citation-count#15]
Hello, first of all, thank you very much for improving this plugin. It has been very convenient for me. However, I have noticed a bug in the new version. The Google Scholar verification keeps popping up repeatedly, even after successful verification, and cannot be closed.

**Comment by justinribeiro** [comment]
I haven't been able to duplicate this in the latest version so far, but this behavior in-particular I've noticed to be rather version agnostic. Usually this occurs for reasons outside the plug-in itself; either large volumes of lookups (in app or just against the IP address your on). When you do it with the plug-in for lots of stuff, it'll try to stagger/randomize the lookup timing, but sometimes GS gets angry and just hammers you with verification.

The workaround is to kill Zotero and let GS cool off for a bit and then attempt to use the plugin again. This _usually_ does the trick (when I was patching the recent GS UI change for instance, I hammered GS and had to let it cool off the IP ban to prevent the issue your describing for a couple of hours).

I'll keep this ticket open while I run more tests in the mean time.

**Comment by romankupkovic** [comment]
I still experience this problem in 3.2.2

Google Scholar Captcha shows up after some warning and the Captcha won't complete after multiple tries.

When closing the Google Scholar window the same warning from before reappears and the Captcha opens again until Zotero is terminated.

**Comment by justinribeiro** [comment]
Re-written potions of 4.1.1 should resolve this (hopefully :-)
