### ISSUE TITLE
BUG: Appeared:'ZSCC:NoData'

### ISSUE THREAD

**Issue by MrGongqi** [justinribeiro/zotero-google-scholar-citation-count#17]
The plugin is currently experiencing a bug where every time you try to search for reference counts, it displays "ZSCC:NoData". Similarly, when you try to add a webpage, the plugin automatically generates the same error message. The cause of this issue is unknown. How can I resolve this problem?
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/49467246/461ad8a2-d988-4769-bcec-a52d3fcc50ea)

**Comment by justinribeiro** [comment]
Which version of the plugin are you using? My version doesn't use the ZSCC
is why I ask, and recent changes to Google Scholar require at the least the
most recent version to deal with changes to pull the citation count.

**Comment by MrGongqi** [comment]
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/49467246/8657ab5f-b8e2-4ecf-8de1-80388c58975b)
PS: I am using Zotero 6.0.26.
Thank you .

**Comment by justinribeiro** [comment]
Closing in favor of Zotero 7 work.
