### ISSUE TITLE
Could you add the date information to the GSCC？

### ISSUE THREAD

**Issue by xuey06** [justinribeiro/zotero-google-scholar-citation-count#2]
As the title mentioned, the last updated date information is needed. Could you add it to the GSCC iterms?

**Comment by justinribeiro** [comment]
I can add the date, sure thing. If there something you want it to do with the date (e.g. update comparison)?

**Comment by calbraz** [comment]
Plus one for this feature request. Maybe not used by all, but I am quite sure many rely on this extension to carry on their scientific systematic literature research. GSCC value is time-dependent value and having the record on when GSCC was performed would be a great plus for us, happy users.

**Comment by justinribeiro** [comment]
With version 7 landed, I'll take this one back up (since I can now custom column it making it a bit more usable)

**Comment by justinribeiro** [comment]
Resolved in #45 

![image](https://github.com/user-attachments/assets/813b08ec-1438-4af6-b292-085f95e47cc1)
