### ISSUE TITLE
Incorrect fetching for paper with similar names

### ISSUE THREAD

**Issue by AVHopp** [justinribeiro/zotero-google-scholar-citation-count#20]
First of all: Thank you for your add-on! It works very well for me and I am thankful for your work here!

When updating the citations, I observed an error: The famous paper "Attention is all you need" , which has more than 100000 citations only has 359 citations according to your add-on. I did some research, and I think I found the reason: There is another paper with the title "Attention is all you need in speech separation" which has exactly 359 citations.
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/84016733/75ad1cd3-633c-4ca3-b9ea-7fc882157ec5)
<img width="844" alt="image" src="https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/84016733/f35bb0c2-814e-4c0f-8b2c-794953879729">

So my guess is that your add-on confuses these two papers, since they start with the exact same phrase.

**Comment by justinribeiro** [comment]
Humm, that's very strange; the plugin doesn't just look for title, it accounts for author as well. Testing it today, I see the proper number of citations pulled (ignore the Zotero 7 look, I'm testing against latest):
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/643503/28e44a1b-e29b-445f-82a0-e4904845f635)

Does your ref in Zotero have the authors/other metadata?

**Comment by AVHopp** [comment]
This is the metadata that I have:
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/84016733/d08937e2-673a-4c35-84fb-fb8fdc271ecb)
I'm on Zotero 6.0.30 if that helpgs

**Comment by pspdada** [comment]
I encountered the exact same issue on my Zotero 7, where "Attention Is All You Need" has been assigned the citation count of the paper "Attention is all you need in speech separation". I have version 4.0.0 of the plugin installed.
Zotero version is 7.0.0-beta.101+220bb4383 (64-bit)

**Comment by justinribeiro** [comment]
My suspicion is that this is a Google Scholar issue that I won't be able to solve. Sometimes Google Scholar returns different results based on region, making both "perfect" paper matching and counts incorrect (see as another example https://github.com/justinribeiro/zotero-google-scholar-citation-count/issues/18#issuecomment-1795857736)

I'm going to close this in favor of some additional work I'm doing as part of the next version which tries to resolve items of this type. Thank you for reporting!
