### ISSUE TITLE
Zotero 7 - no settings for GSCC

### ISSUE THREAD

**Issue by kbdragon** [justinribeiro/zotero-google-scholar-citation-count#21]
I followed the instructions in the Zotero 7 support thread to install the extension - works great. 
I tried to follow the instruction to set some settings, but I can't see any settings in the advanced prefs editor.
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/113253861/02fef351-32b0-4936-a232-9dbf795063c7)

Any info I should provide?

**Comment by pietro-sillano** [comment]
same behaviour

**Comment by justinribeiro** [comment]
Yeaaaa this is because the GSCC settings port was a little flacky when I first cut this. Let me circle back, I'll get them back in there. :+1:

**Comment by justinribeiro** [comment]
Redesigned (and now extended) preferences committed in d681f83; coming in v4.1 later this week.

![image](https://github.com/user-attachments/assets/1d921482-e083-433a-9da7-f0b60f604320)
