### ISSUE TITLE
zotero 7 wrong citation count

### ISSUE THREAD

**Issue by yjavaherian** [justinribeiro/zotero-google-scholar-citation-count#22]
hi. i just built the zotero 7 version myself.
it works, but for some reason the reported citation count does not match that of google scholar ( for some papers)!

e.g. 
Emergent Communication of Generalizations (google scholar citation count: 32, plugin: 55)
Making sense of raw input (google scholar citation citation: 34, plugin: 314)

but for others it reports correctly
e.g.
GFlowNet Foundations (google scholar and plugin: 121)

**Comment by yjavaherian** [comment]
it looks like the problem is in the output of the google scholar for `targetUrl`.
for example for "making sense of raw input 2021 " the targeturl is :
`https://scholar.google.com/scholar?hl=en&q=Making%20sense%20of%20raw%20input&as_epq=&as_occt=title&num=1&as_sauthors=Evans+Bo%C5%A1njak+Buesing&as_ylo=2019&as_yhi=2023`

and when you open this url the actual paper is not present in this result!
strangely changing the year filter to as_ylo=2021&as_yhi=2021  fixes this!!

i think the problem is on the side of google scholar since 2021 is between 2019 and 2023 but the the actual paper is missing from the output of 2019...2023 filter. very strange 😕

i suppose changing this line

``` js
    if (year) {
      paramDateRange = `&as_ylo=${year - 2}&as_yhi=${year + 2}`;
    }
```
to 
``` js
    if (year) {
      paramDateRange = `&as_ylo=${year}&as_yhi=${year}`;
    }
```
should fix the problem.

**Comment by Aman-4-Real** [comment]
THX for the authors' efforts! I also noticed some count errors in this case. Looking forward to the revised release!

**Comment by Aman-4-Real** [comment]
> it looks like the problem is in the output of the google scholar for `targetUrl`. for example for "making sense of raw input 2021 " the targeturl is : `https://scholar.google.com/scholar?hl=en&q=Making%20sense%20of%20raw%20input&as_epq=&as_occt=title&num=1&as_sauthors=Evans+Bo%C5%A1njak+Buesing&as_ylo=2019&as_yhi=2023`
> 
> and when you open this url the actual paper is not present in this result! strangely changing the year filter to as_ylo=2021&as_yhi=2021 fixes this!!
> 
> i think the problem is on the side of google scholar since 2021 is between 2019 and 2023 but the the actual paper is missing from the output of 2019...2023 filter. very strange 😕
> 
> i suppose changing this line
> 
> ```js
>     if (year) {
>       paramDateRange = `&as_ylo=${year - 2}&as_yhi=${year + 2}`;
>     }
> ```
> 
> to
> 
> ```js
>     if (year) {
>       paramDateRange = `&as_ylo=${year}&as_yhi=${year}`;
>     }
> ```
> 
> should fix the problem.

I am just wondering where I can change this line?

**Comment by yjavaherian** [comment]
it's here:
https://github.com/justinribeiro/zotero-google-scholar-citation-count/blob/bd2e8f83e72f9e1f72158762b5a6abd06c6d3740/src/chrome/content/gscc.js#L703-L705

**Comment by Aman-4-Real** [comment]
> it's here:
> 
> https://github.com/justinribeiro/zotero-google-scholar-citation-count/blob/bd2e8f83e72f9e1f72158762b5a6abd06c6d3740/src/chrome/content/gscc.js#L703-L705

THX!!!!!

**Comment by justinribeiro** [comment]
See this comment regarding the behavior and limitation of Google Scholar when it comes to "perfect" matching and why I won't make this revision: https://github.com/justinribeiro/zotero-google-scholar-citation-count/issues/18#issuecomment-1795857736
