### ISSUE TITLE
help for localization language

### ISSUE THREAD

**Issue by jlu511** [justinribeiro/zotero-google-scholar-citation-count#24]
thank you for amazing work.

I try to localize this plugin in chinese. I copy \locale\en-US\* to creat  \locale\zh-CN\* . 
then I change three files， gscc.ftl  gscc.properties  overlay.dtd， as follow：
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/64378673/f5f6131f-fabd-487a-b0df-443eca3439db)
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/64378673/733eceed-b65e-468f-93c0-35f6e94ead05)
![image](https://github.com/justinribeiro/zotero-google-scholar-citation-count/assets/64378673/0aea8f21-7ecf-43b5-8b28-ab24818f3194)

but it does not work. 
what is wrong?

Please ignore my poor English

**Comment by justinribeiro** [comment]
I suspect this is a bug in the way FTL is being applied. If you like, please make a PR with that translation, and I'll work on the getting the bug fixed the next couple of days. :+1:

**Comment by jlu511** [comment]
Sorry, I don't know programming and don't know how to provide PR. But I can provide translated documents. thanks
[zh-CN.zip](https://github.com/justinribeiro/zotero-google-scholar-citation-count/files/15419952/zh-CN.zip)

**Comment by justinribeiro** [comment]
Patched in [87748dd](https://github.com/justinribeiro/zotero-google-scholar-citation-count/commit/87748dd60c4c71b2a3ada1e0be199e7d86083859); rolling out in v4.1 later this week.
