### ISSUE TITLE
Plugin unresponsive in zotero7

### ISSUE THREAD

**Issue by MrGongqi** [justinribeiro/zotero-google-scholar-citation-count#26]
I installed the 4.0.0 plugin, but when I use it to pull citations, it doesn't respond at all (this is my first time pulling citations, and I can use Google). 
No matter how many times I try to restart zotero7, it still remains unresponsive.

**Comment by justinribeiro** [comment]
At AoM, will take a look when conf wraps mid-week 👍

**Comment by MrGongqi** [comment]
Thank you very much and hope you have a pleasant trip.

**Comment by justinribeiro** [comment]
Checking on this, I'm struggling to recreate the freeze. What platform are you on or any other hints as to your use case would be helpful!

**Comment by MrGongqi** [comment]
Hello, I can't reproduce the situation now.  But I have indeed encountered this situation several times. The plug-in sometimes becomes unresponsive, and it is not due to multiple uses in a short period of time.

**Comment by justinribeiro** [comment]
Given the intermittence, I'll add some additional debugging output and run it in a loop, see if I can track down the issue.

**Comment by justinribeiro** [comment]
v4.1.1 should now resolve this.

**Comment by MrGongqi** [comment]
Thank you. 
Your plugin is the best, thank you so much for all your hard work.
