### ISSUE TITLE
Check <> Code Dowload V4.1.1

### ISSUE THREAD

**Issue by drestrepoh98** [justinribeiro/zotero-google-scholar-citation-count#34]
Hi very a nub in the GitHub World.

I am using Zotero and your Plug in is amazing.

It took me some extra time to realize that only dowloading the plug in from the tags is actually working and the button of <> Code Dowload V4.1.1 for Zotero 7x is not working. It shows an error.

Else amazing work with the Plug in!

Regards!

**Comment by justinribeiro** [comment]
Ah, thanks for the check, let me fix that......
