### ISSUE TITLE
Add a update date

### ISSUE THREAD

**Issue by BBuniverse** [justinribeiro/zotero-google-scholar-citation-count#37]
This is an awesome project that helps me easily manage my library.

Would it be possible to add an update date [e.g., 2024-11-24] after the GSCC:xxxxx? This would be helpful for tracking citation increases by comparing with previous records.

![image](https://github.com/user-attachments/assets/18dad2d2-356d-4059-bf9f-5a2978631275)

Thank you very much!!!

**Comment by justinribeiro** [comment]
Will be in next release!

![image](https://github.com/user-attachments/assets/4326f8c2-62bb-4847-b612-9cfbe484c008)
